### PR TITLE
openmpi-mpi v4.0.5

### PR DESCRIPTION
**Pull request by nsls2forge**
It is very likely that the current package version for this feedstock is out of date.
Notes for merging this PR:
1. Feel free to push to the bot's branch to update this PR if needed.
2. The bot will almost always only open one PR per version.
Checklist before merging this PR:
- [ ] Dependencies have been updated if changed: see [upstream](https://github.com/open-mpi/ompi)
- [ ] Tests have passed 
- [ ] Updated license if changed and `license_file` is packaged 

Note that the bot will stop issuing PRs if more than 3 Version bump PRs generated by the bot are open. If you don't want to package a particular version please close the PR.

Closes: #3

Here is a list of all the pending dependencies (and their versions) for this repo. The first package is the current feedstock package. Please double check all dependencies before merging.

# Feedstock Packages Build Status

| Repo | Build <br/> Health | nsls2forge <br/> PyPI <br/> defaults <br/> conda-forge <br/> GitHub <br/> Versions | Downloads|
|:-------:|:-----------:|:---------------:|:--------------:|
|[openmpi-mpi](https://github.com/nsls-ii-forge/openmpi-mpi-feedstock)|[Build Status](https://dev.azure.com/nsls2forge/nsls2forge/_build) <br/> [Code Health](https://landscape.io/github/nsls-ii-forge/openmpi-mpi-feedstock/master)|[nsls2forge version](https://anaconda.org/nsls2forge/openmpi-mpi) <br/> [PyPI version](https://pypi.org/project/openmpi-mpi/) <br/> [defaults version](https://anaconda.org/anaconda/openmpi-mpi) <br/> [conda-forge version](https://anaconda.org/conda-forge/openmpi-mpi) <br/> [GitHub version](https://github.com/open-mpi/ompi)|[Downloads](https://anaconda.org/nsls2forge/openmpi-mpi)|
|[openmpi-mpi](https://github.com/nsls-ii-forge/openmpi-mpi-feedstock)|[Build Status](https://dev.azure.com/nsls2forge/nsls2forge/_build) <br/> [Code Health](https://landscape.io/github/nsls-ii-forge/openmpi-mpi-feedstock/master)|[nsls2forge version](https://anaconda.org/nsls2forge/openmpi-mpi) <br/> [PyPI version](https://pypi.org/project/openmpi-mpi/) <br/> [defaults version](https://anaconda.org/anaconda/openmpi-mpi) <br/> [conda-forge version](https://anaconda.org/conda-forge/openmpi-mpi) <br/> [GitHub version](https://github.com/open-mpi/ompi)|[Downloads](https://anaconda.org/nsls2forge/openmpi-mpi)|

### CODE REVIEW

**Comment by mrakitin** [comment]
@leofang, this stopped working for the cloud docker execution. What would be your suggestions?

**Comment by leofang** [comment]
Let me power-cycle and see if it's a transient thing.

**Comment by leofang** [comment]
No idea what's wrong. Looking into this locally...

**Comment by leofang** [comment]
@mrakitin I figured it out. Somehow our setup is no longer able to pick up `nvcc_linux-64` from conda-forge. I was able to reproduce the failure locally, and confirmed that changing `channel_sources` here
https://github.com/nsls-ii-forge/openmpi-mpi-feedstock/blob/84a03e66905b60a89da12c47522a2642d6258e3d/recipe/conda_build_config.yaml#L1-L2
to `nsls2forge,conda-forge,defaults` would fix it. Would you like me to proceed with this solution?

**Comment by leofang** [comment]
Or perhaps `nsls2forge,defaults,conda-forge` is better? What do you think @mrakitin?

**Comment by mrakitin** [comment]
Hi @leofang, sure, let's try to use this sequence of channels (`nsls2forge,defaults,conda-forge`) in `recipe/conda_build_config.yaml` (with subsequent rerendering). As neither `defaults` nor `nsls2forge` have the `nvcc` package, we have to use something else. I think it used to work because older conda-forge ci scripts were always adding the `conda-forge` channel to the list of channels. Then it was fixed, which probably broke this approach.

**Comment by leofang** [comment]
Thanks, @mrakitin, done.

**Comment by mrakitin** [comment]
Neat! Thanks @leofang.

**Pull request merged**
